---
- name: "Przypomnienie mechanizmu Handlers"
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: "1. Zapisanie tekstu do pliku w /tmp"
      ansible.builtin.copy:
        content: "Status: Rozgrzewka zaliczona"
        dest: /tmp/powtorka_stanu.txt
      # Przypomnienie: notify musi idealnie pasować do nazwy handlera na dole
      notify: "Komunikat sukcesu"

  handlers:
    - name: "Komunikat sukcesu"
      ansible.builtin.debug:
        msg: "HANDLER: Zauważyłem zmianę w pliku! Wszystko działa jak należy."