- name: "Projekt Finalny - mix wszystkiego"
  connection: local
  hosts: space_stations
  become: true

  vars:
    lista_folderow:
      - "{{ sciezka_bazy }}/config"
      - "{{ sciezka_bazy }}/db"
  tasks: 
    block:
      - name: "Tworzenie folderu petla"
        ansible.builtin.file:
          path: "{{ item }}"
          state: directory
          mode: "0755"
        loop: " {{ lista_folderow }}"
      
      - name: "Sprawdzanie wersji"
        ansible.builtin.debug:
          msg: "Weryfikacja wersji krytycznej zakończona sukcesem!"
        when:  wersja_systemu == "v2.4.1"

      - name: "Tworzenie konfigu"
        ansible.builtin.copy:
          dest: "/tmp/spaceport/config/launch.cfg"
          content: "WEZEL={{ nazwa_wezla }} | TOKEN={{ tajny_token }}"
        notify: "Restart systemow portu"

    rescue:
      - name: "Wyświetlenie bledu"
        ansible.builtin.debug:
          msg: "AWARIA: Wykryto błąd w konfiguracji Kosmodromu! Cofam zmiany."

  handlers:
    - name: "Restart systemow portu"
      ansible.builtin.debug:
        msg: "HANDLER: Wykryto nową konfigurację. Systemy startowe zrestartowane pomyślnie!"   