---
- name: Zaawansowane zarzadzanie uzytkownikami z uzyciem Vault i Petli
  hosts: localhost
  connection: local
  become: true

  # 1. Kazemy Ansible wczytac nasz zaszyfrowany plik jako zrodlo zmiennych
  vars_files:
    - sekrety.yml

  tasks:
    - name: "AUTOMATYZACJA: Tworzenie kont pracownikow z listy"
      ansible.builtin.user:
        name: "{{ item.login }}"
        state: present
        shell: /bin/bash
      # To jest petla! Przeleci przez cala liste z pliku sekrety.yml
      loop: "{{ lista_pracownikow }}"

    - name: "BEZPIECZENSTWO: Dodawanie wybranych osob do grupy administratorow"
      ansible.builtin.user:
        name: "{{ item.login }}"
        groups: sudo
        append: yes
      loop: "{{ lista_pracownikow }}"
      # To jest warunek! To zadanie wykona sie TYLKO dla osob, ktore maja uprawnienia 'sudo'
      when: item.uprawnienia == 'sudo'
