---
- name: Zaawansowane zarzadzanie uzytkownikami z uzyciem Vault i Petli
  hosts: localhost
  connection: local
  become: true

  vars_files:
    - sekrety.yml

  tasks:
    - name: "AUTOMATYZACJA: Tworzenie kont pracownikow z listy"
      ansible.builtin.user:
        name: "{{ item.login }}"
        state: present
        shell: /bin/bash
      loop: "{{ lista_pracownikow }}"

    - name: "BEZPIECZENSTWO: Dodawanie wybranych osob do grupy administratorow"
      ansible.builtin.user:
        name: "{{ item.login }}"
        groups: sudo
        append: yes
      loop: "{{ lista_pracownikow }}"
      when: item.uprawnienia == 'sudo'
