- name: "Instalacja curl, git i htop"
  ansible.builtin.apt:
    name:
      - curl
      - git
      - htop
    state: present
- name: "Stworzenie folderu Admina"
  ansible.builtin.file:
    path: /opt/narzedzia_devops
    state: directory
    mode: '0700'
- name: "Kopiowanie pliku wersja.txt do folderu Admina"
  ansible.builtin.template:
    src: wersja.txt.j2
    dest: /opt/narzedzia_devops/wersja.txt
    mode: '0600'
  